drop table if exists account cascade;
drop table if exists announcement cascade;
drop table if exists business cascade;
drop table if exists business_category cascade;
drop table if exists category cascade;
drop table if exists chat cascade;
drop table if exists chat_room cascade;
drop table if exists contract cascade;
drop table if exists employee cascade;
drop table if exists employer cascade;
drop table if exists exteranl_carrer cascade;
drop table if exists flavored cascade;
drop table if exists offer_employment cascade;
drop table if exists possible_board cascade ;
drop table if exists review cascade;
drop table if exists scrap cascade;

create table account
(
    account_age                 integer,
    account_deleted             BOOLEAN DEFAULT false,
    account_registered_datetime timestamp(6),
    account_unique_id           bigint generated by default as identity,
    updated_at                  timestamp(6),
    account_email               varchar(255),
    account_id                  varchar(255),
    account_name                varchar(255),
    account_nickname            varchar(255),
    account_nationality         varchar(255),
    account_role                varchar(255),
    account_password            varchar(255),
    account_phone_number        varchar(255),
    account_profile_image       varchar(255),
    account_sex                 varchar(255),
    account_star_rating         float,
    account_work_count          integer,
    account_open_status         BOOLEAN DEFAULT true,
    primary key (account_unique_id)
);
create table announcement
(
    view_count           int DEFAULT 0,
    announcement_id      bigint generated by default as identity,
    created_at           timestamp(6),
    updated_at           timestamp(6),
    announcement_content varchar(255),
    announcement_title   varchar(255),
    announcement_type    varchar(255),
    primary key (announcement_id)
);

create table business
(
    business_open_date           date,
    business_employer_id         bigint,
    business_id                  bigint generated by default as identity,
    created_at                   timestamp(6),
    updated_at                   timestamp(6),
    business_location            varchar(255),
    business_name                varchar(255),
    business_registration_number varchar(255),
    representation_name          varchar(255),
    primary key (business_id)
);

create table business_category
(
    business_category_id bigint generated by default as identity,
    business_id          bigint,
    categorey_id         bigint,
    created_at           timestamp(6),
    updated_at           timestamp(6),
    primary key (business_category_id)
);
create table category
(
    category_id   bigint generated by default as identity,
    created_at    timestamp(6),
    updated_at    timestamp(6),
    category_name varchar(255),
    primary key (category_id)
);
create table chat
(
    chat_deleted       BOOLEAN DEFAULT false,
    account_unique_id  bigint,
    chat_id            bigint generated by default as identity,
    chat_register_date timestamp(6),
    chat_room_id       bigint,
    chat_content       varchar(255),
    primary key (chat_id)
);

create table chat_room
(
    chat_room_id           bigint generated by default as identity,
    suggest_generated_date timestamp(6),
    suggest_id             bigint unique,
    primary key (chat_room_id)
);

create table contract
(
    contract_hourly_pay integer,
    contract_succeded   boolean DEFAULT false,
    contract_end_time   timestamp(6),
    contract_id         bigint generated by default as identity,
    contract_start_time timestamp(6),
    created_at          timestamp(6),
    suggest_id          bigint unique,
    updated_at          timestamp(6),
    primary key (contract_id)
);


create table employee
(
    employee_star_rating float(24),
    employee_work_count  integer,
    account_id           bigint unique,
    created_at           timestamp(6),
    employee_id          bigint generated by default as identity,
    updated_at           timestamp(6),
    employee_nickname    varchar(255),
    primary key (employee_id)
);

create table employer
(
    account_id        bigint unique,
    created_at        timestamp(6),
    employer_id       bigint generated by default as identity,
    updated_at        timestamp(6),
    employer_nickname varchar(255),
    primary key (employer_id)
);

create table exteranl_carrer
(
    created_at       timestamp(6),
    employee_id      bigint,
    id               bigint generated by default as identity,
    updated_at       timestamp(6),
    business_name    varchar(255),
    part_time_period varchar(255),
    primary key (id)
);

create table flavored
(
    category_id bigint,
    created_at  timestamp(6),
    employee_id bigint,
    flavored_id bigint generated by default as identity,
    updated_at  timestamp(6),
    primary key (flavored_id),
    unique (employee_id, category_id)
);

create table offer_employment
(
    suggest_hourly_pay    integer,
    suggest_readed        boolean DEFAULT false,
    suggest_succeded      boolean DEFAULT false,
    business_id           bigint unique,
    employee_id           bigint unique,
    suggest_end_time      timestamp(6),
    suggest_id            bigint generated by default as identity,
    suggest_register_time timestamp(6),
    suggest_start_time    timestamp(6),
    primary key (suggest_id)
);

create table possible_board
(
    created_at          timestamp(6),
    employee_id         bigint,
    possible_end_time   timestamp(6),
    possible_id         bigint generated by default as identity,
    possible_start_time timestamp(6),
    updated_at          timestamp(6),
    primary key (possible_id)
);

create table review
(
    review_star_point integer,
    created_at        timestamp(6),
    suggest_id        bigint generated by default as identity,
    updated_at        timestamp(6),
    review_content    varchar(255),
    primary key (suggest_id)
);


create table scrap
(
    created_at           timestamp(6),
    employee_employee_id bigint,
    employer_employer_id bigint,
    scrap_id             bigint generated by default as identity,
    updated_at           timestamp(6),
    primary key (scrap_id)
);

alter table if exists business
    add constraint FKrmvi7a8hp1gvo4fs2vifp1u8s
        foreign key (business_employer_id)
            references employer;


alter table if exists business_category
    add constraint FKpphxqd3m7af7xsylvpb26gqp8
        foreign key (business_id)
            references business;

alter table if exists business_category
    add constraint FKh2g43n4c0mukqvpami4x0st36
        foreign key (categorey_id)
            references category;

alter table if exists chat
    add constraint FKijoxkthso6n3r8bian3xu8dau
        foreign key (account_unique_id)
            references account;

alter table if exists chat
    add constraint FK44b6elhh512d2722l09i6qdku
        foreign key (chat_room_id)
            references chat_room;

alter table if exists chat_room
    add constraint FKs40aoy58klwk8k66k90vpvxek
        foreign key (suggest_id)
            references offer_employment;

alter table if exists contract
    add constraint FKcvp9vmfpl0bm6b6c63l2ormj6
        foreign key (suggest_id)
            references offer_employment;

alter table if exists employee
    add constraint FKcfg6ajo8oske94exynxpf7tf9
        foreign key (account_id)
            references account;

alter table if exists employer
    add constraint FKj4pj26t1ecnkh85f5dehhvj95
        foreign key (account_id)
            references account;

alter table if exists exteranl_carrer
    add constraint FK47yjhdvwno2buwixnbbiipuvs
        foreign key (employee_id)
            references employee;

alter table if exists flavored
    add constraint FK5fko12aoyvyiogwi3bxr7p5pf
        foreign key (category_id)
            references category;

alter table if exists flavored
    add constraint FKgp8oorhip9jq4ulnlj3qo6tqj
        foreign key (employee_id)
            references employee;

alter table if exists offer_employment
    add constraint FK8xi6px87at3h94jr4434dxt6h
        foreign key (business_id)
            references business;

alter table if exists offer_employment
    add constraint FK8d521thyf88sosfv3kdni94cc
        foreign key (employee_id)
            references employee;

alter table if exists possible_board
    add constraint FKpo0s6j32cqd4dqtregricmak0
        foreign key (employee_id)
            references employee;

alter table if exists scrap
    add constraint FKqml51wgiigjp3arbctk13hk1x
        foreign key (employee_employee_id)
            references employee;

alter table if exists scrap
    add constraint FK7atea93v4sptxh64isjnikhgm
        foreign key (employer_employer_id)
            references employer;